package com.liu.dao;

import com.liu.bean.CapitalFlow;

import java.util.List;

public interface CapitalFlowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capital_flow
     *
     * @mbg.generated Sat Feb 19 10:18:30 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capital_flow
     *
     * @mbg.generated Sat Feb 19 10:18:30 CST 2022
     */
    int insert(CapitalFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capital_flow
     *
     * @mbg.generated Sat Feb 19 10:18:30 CST 2022
     */
    CapitalFlow selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capital_flow
     *
     * @mbg.generated Sat Feb 19 10:18:30 CST 2022
     */
    List<CapitalFlow> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table capital_flow
     *
     * @mbg.generated Sat Feb 19 10:18:30 CST 2022
     */
    int updateByPrimaryKey(CapitalFlow record);
}