package com.liu.dao;

import com.liu.bean.PlantingTask;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface PlantingTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table planting_task
     *
     * @mbg.generated Sat Feb 19 10:18:30 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table planting_task
     *
     * @mbg.generated Sat Feb 19 10:18:30 CST 2022
     */
    int insert(PlantingTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table planting_task
     *
     * @mbg.generated Sat Feb 19 10:18:30 CST 2022
     */
    PlantingTask selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table planting_task
     *
     * @mbg.generated Sat Feb 19 10:18:30 CST 2022
     */
    List<PlantingTask> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table planting_task
     *
     * @mbg.generated Sat Feb 19 10:18:30 CST 2022
     */
    int updateByPrimaryKey(PlantingTask record);
}