package com.liu.dao;

import com.liu.bean.StaffApply;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface StaffApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_apply
     *
     * @mbg.generated Sat Feb 19 10:18:30 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_apply
     *
     * @mbg.generated Sat Feb 19 10:18:30 CST 2022
     */
    int insert(StaffApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_apply
     *
     * @mbg.generated Sat Feb 19 10:18:30 CST 2022
     */
    StaffApply selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_apply
     *
     * @mbg.generated Sat Feb 19 10:18:30 CST 2022
     */
    List<StaffApply> selectAll0();

    List<StaffApply> selectAllNo0();

    void deleteByList(@Param("idList") List<Integer> idList);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_apply
     *
     * @mbg.generated Sat Feb 19 10:18:30 CST 2022
     */
    int updateByPrimaryKey(StaffApply record);

    void acceptApply(@Param("applyList") List<Integer> applyList);
    void rejectApply(@Param("applyList") List<Integer> applyList);
}