package com.liu.dao;

import com.liu.bean.StaffApply;

import java.util.List;

public interface StaffApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_apply
     *
     * @mbg.generated Sat Feb 19 10:18:30 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_apply
     *
     * @mbg.generated Sat Feb 19 10:18:30 CST 2022
     */
    int insert(StaffApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_apply
     *
     * @mbg.generated Sat Feb 19 10:18:30 CST 2022
     */
    StaffApply selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_apply
     *
     * @mbg.generated Sat Feb 19 10:18:30 CST 2022
     */
    List<StaffApply> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_apply
     *
     * @mbg.generated Sat Feb 19 10:18:30 CST 2022
     */
    int updateByPrimaryKey(StaffApply record);
}