package com.liu.dao;

import com.liu.bean.SystemRecord;

import java.util.List;

public interface SystemRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_record
     *
     * @mbg.generated Sat Feb 19 10:18:30 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_record
     *
     * @mbg.generated Sat Feb 19 10:18:30 CST 2022
     */
    int insert(SystemRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_record
     *
     * @mbg.generated Sat Feb 19 10:18:30 CST 2022
     */
    SystemRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_record
     *
     * @mbg.generated Sat Feb 19 10:18:30 CST 2022
     */
    List<SystemRecord> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_record
     *
     * @mbg.generated Sat Feb 19 10:18:30 CST 2022
     */
    int updateByPrimaryKey(SystemRecord record);
}