package com.liu.dao;

import com.liu.bean.PlantingTask;
import com.liu.bean.TaskList;
import com.liu.bean.TrimTask;
import com.liu.bean.WateringTask;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface TaskListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_list
     *
     * @mbg.generated Sat Feb 19 10:18:30 CST 2022
     */
    int deleteByPrimaryKey(Integer tid);

    Integer insert(TaskList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_list
     *
     * @mbg.generated Sat Feb 19 10:18:30 CST 2022
     */
    TaskList selectByPrimaryKey(Integer tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_list
     *
     * @mbg.generated Sat Feb 19 10:18:30 CST 2022
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_list
     *
     * @mbg.generated Sat Feb 19 10:18:30 CST 2022
     */
    int updateByPrimaryKey(TaskList record);
}