package com.liu.dao;

import com.liu.bean.TreeState;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
import java.util.Map;

@Mapper
public interface TreeStateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tree_state
     *
     * @mbg.generated Sat Feb 19 10:18:30 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tree_state
     *
     * @mbg.generated Sat Feb 19 10:18:30 CST 2022
     */
    int insert();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tree_state
     *
     * @mbg.generated Sat Feb 19 10:18:30 CST 2022
     */
    TreeState selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tree_state
     *
     * @mbg.generated Sat Feb 19 10:18:30 CST 2022
     */
    List<TreeState> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tree_state
     *
     * @mbg.generated Sat Feb 19 10:18:30 CST 2022
     */
    int updateByPrimaryKey(TreeState record);

    List<Map<String,Object>> allTypeTree(Integer id);
}