package com.liu.dao;

import com.liu.bean.WateringTask;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface WateringTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watering_task
     *
     * @mbg.generated Sat Feb 19 10:18:30 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watering_task
     *
     * @mbg.generated Sat Feb 19 10:18:30 CST 2022
     */
    int insert(WateringTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watering_task
     *
     * @mbg.generated Sat Feb 19 10:18:30 CST 2022
     */
    WateringTask selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watering_task
     *
     * @mbg.generated Sat Feb 19 10:18:30 CST 2022
     */
    List<WateringTask> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table watering_task
     *
     * @mbg.generated Sat Feb 19 10:18:30 CST 2022
     */
    int updateByPrimaryKey(WateringTask record);
}